# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Stephen Harney
  email: your-email@domain.com
description: "A blog."

# Build settings
remote_theme: jekyll/minima

<img src="https://raw.githubusercontent.com/StephenHarney/_config.ynl/main/docs/assets/C++Project.png" width="400" height="300">
