# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Stephen Harney
  email: your-email@domain.com
description: "Matrix DigitalRain Project c++ blog"

# Build settings
remote_theme: jekyll/minima

